version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: research_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - research_network

  research_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research_app
    ports:
      - "3000:3000"  # Expose the app port (if needed)
    environment:
      - OLLAMA_URL=http://ollama:11434
      - RESEARCH_DIR=/app/research
    volumes:
      - .:/app
      - research_data:/app/research
    depends_on:
      - ollama
    networks:
      - research_network

volumes:
  ollama_data:
  research_data:

networks:
  research_network:
    driver: bridge