version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: research_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - research_network

  neo4j:
    image: neo4j:5.13
    container_name: research_neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/research123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    networks:
      - research_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: research_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - research_network

  research_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research_app
    ports:
      - "3000:3000"  # Expose the app port (if needed)
    environment:
      - OLLAMA_URL=http://ollama:11434
      - NEO4J_URL=bolt://neo4j:7687
      - ES_HOST=http://elasticsearch:9200
      - RESEARCH_DIR=/app/research
    volumes:
      - .:/app
      - research_data:/app/research
    depends_on:
      - ollama
      - neo4j
      - elasticsearch
    networks:
      - research_network

volumes:
  ollama_data:
  neo4j_data:
  elasticsearch_data:
  research_data:

networks:
  research_network:
    driver: bridge