# config/settings.yml
ollama:
  base_url: "http://localhost:11434"
  model: "research-assistant-reasoning-model"
  parameters:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 4096

research:
  max_iterations: 7
  depth_factor: 0.8
  novelty_threshold: 0.65
  max_parallel_requests: 3

output:
  default_format: "markdown"
  stylesheet: "apa"
  auto_abstract: true